### ISSUE TITLE
Relative Path

### ISSUE THREAD

**Issue by LintonBlack** [andrewbober/xsd2jsonschema#2]
Hi Andrew,

nice work !
I was trying to add some imbricated schema and It return that I can have a Schema from another repository than the example one.
ex : example/BaseType.xsd  
can not import a schema coming from 
example/test/subschem.xsd  
which can get a schema from
example/test/other/subschema.xsd

if it makes sens.

any thought ?

**Comment by andrewbober** [comment]
Hi Phil,

I appreciate you taking the time to submit this issue and I apologize for the delayed response.  I just noticed this issue was filed.  I am finishing up a a significant update that I hope to push by the end of the week.  I will include a more comprehensive example that addresses this issue.

Question: What validator are you using?

Kind Thank you,

Andy

**Comment by andrewbober** [comment]
This is is resolved.  File handling was removed from the library so it can more easily be embedded into and utilized by other libraries or applications.
